In [21]:
import pandas as pd
from pm4py.objects.conversion.log import converter as log_converter
from pm4py.objects.log.importer.xes import importer as xes_importer

In [2]:
log = xes_importer.apply('data/PurchasingExample.xes')
event_log = log_converter.apply(log, variant=log_converter.Variants.TO_DATA_FRAME)

parsing log, completed traces ::   0%|          | 0/608 [00:00<?, ?it/s]

In [3]:
event_log_by_case = event_log.groupby(by='case:concept:name')
event_log_by_case.groups.keys()

dict_keys(['1', '10', '100', '1004', '1008', '1009', '101', '1011', '1015', '1018', '102', '1020', '1021', '1022', '1023', '1025', '103', '1031', '1033', '1035', '104', '1041', '1042', '1044', '1047', '1048', '1052', '1057', '106', '1060', '1063', '1065', '1066', '1068', '107', '1079', '1080', '1085', '1088', '109', '1090', '1094', '11', '110', '1104', '111', '1111', '1114', '1116', '1118', '112', '1123', '1128', '1141', '1144', '1146', '115', '1151', '1153', '1158', '1160', '1161', '117', '1177', '1178', '1179', '118', '1182', '1184', '1187', '119', '1191', '1192', '1197', '1198', '12', '120', '1212', '1214', '1215', '122', '1220', '1225', '1227', '123', '124', '1242', '125', '1255', '1259', '127', '128', '1282', '1284', '1287', '129', '1290', '1294', '1298', '1299', '13', '1300', '1305', '1308', '1309', '1310', '132', '1328', '133', '1337', '1338', '134', '1347', '135', '1353', '1358', '136', '1360', '1361', '1362', '1366', '1367', '1368', '137', '1375', '1377', '1378', '138', '1380', '1386', '1387', '1388', '139', '1394', '1395', '14', '140', '1404', '141', '1417', '142', '1420', '1422', '143', '1439', '144', '1448', '145', '1452', '1457', '1458', '146', '1463', '147', '1476', '1477', '1488', '149', '1499', '15', '150', '1500', '1506', '151', '1511', '152', '153', '154', '1547', '155', '1558', '156', '157', '158', '1584', '1585', '159', '1592', '1596', '16', '160', '1613', '162', '1624', '1626', '164', '1682', '169', '17', '170', '171', '172', '1722', '1725', '1749', '175', '1759', '176', '1770', '1773', '1789', '179', '1796', '18', '180', '1817', '182', '183', '185', '1852', '1857', '186', '1871', '1873', '1874', '188', '189', '1892', '19', '1909', '191', '1917', '192', '1920', '1929', '193', '1938', '1941', '1949', '195', '197', '199', '2', '20', '200', '204', '205', '206', '207', '209', '21', '210', '211', '214', '216', '217', '22', '220', '221', '222', '223', '224', '226', '227', '229', '23', '230', '232', '233', '235', '236', '237', '24', '242', '245', '247', '248', '249', '25', '250', '251', '252', '254', '257', '258', '259', '26', '260', '263', '266', '268', '269', '27', '270', '272', '273', '275', '278', '279', '28', '280', '281', '282', '283', '284', '286', '287', '288', '29', '290', '291', '293', '294', '295', '296', '3', '30', '303', '306', '307', '308', '309', '31', '310', '311', '314', '316', '318', '319', '32', '325', '326', '327', '329', '33', '330', '334', '335', '339', '34', '340', '343', '344', '349', '35', '352', '36', '361', '362', '363', '367', '368', '37', '370', '371', '372', '374', '375', '376', '38', '380', '381', '383', '384', '386', '387', '389', '39', '391', '393', '396', '397', '398', '4', '40', '400', '401', '404', '405', '408', '41', '411', '413', '414', '418', '419', '42', '423', '424', '425', '43', '431', '434', '437', '438', '44', '446', '448', '449', '45', '450', '452', '457', '458', '459', '46', '461', '462', '467', '47', '470', '48', '486', '487', '489', '49', '492', '497', '5', '50', '504', '505', '51', '515', '519', '52', '522', '525', '53', '537', '538', '54', '544', '547', '549', '55', '551', '553', '556', '559', '56', '560', '563', '564', '565', '57', '572', '573', '575', '58', '582', '59', '595', '596', '598', '6', '606', '61', '611', '612', '613', '615', '616', '618', '619', '62', '620', '622', '623', '627', '63', '632', '633', '635', '637', '64', '642', '644', '645', '649', '65', '650', '651', '654', '655', '656', '66', '660', '665', '67', '671', '672', '673', '674', '676', '68', '680', '683', '686', '689', '69', '690', '692', '693', '696', '7', '70', '703', '704', '705', '707', '71', '713', '714', '716', '72', '720', '725', '726', '73', '730', '731', '733', '734', '735', '736', '739', '74', '740', '744', '748', '749', '75', '751', '753', '754', '755', '756', '76', '761', '77', '770', '78', '789', '79', '791', '793', '8', '80', '809', '81', '812', '816', '818', '819', '82', '822', '826', '827', '83', '832', '835', '837', '839', '84', '841', '844', '846', '85', '851', '855', '856', '858', '86', '860', '861', '862', '87', '872', '874', '875', '877', '881', '888', '889', '89', '892', '896', '9', '904', '906', '909', '91', '911', '914', '915', '92', '921', '927', '929', '93', '931', '935', '94', '940', '948', '949', '950', '96', '972', '975', '976', '98', '981', '988', '99', '993', '997'])

In [5]:
case = event_log_by_case.get_group('10')
case.head()

,concept:name,lifecycle:transition,org:resource,time:timestamp,Activity,Resource,case:concept:name,case:variant,case:variant-index,case:creator
344,Create Purchase Requisition,start,Esmana Liubiata,2011-01-02 02:52:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco
345,Create Purchase Requisition,complete,Esmana Liubiata,2011-01-02 03:43:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco
346,Create Request for Quotation,start,Immanuel Karagianni,2011-01-02 10:25:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco
347,Create Request for Quotation,complete,Immanuel Karagianni,2011-01-02 10:32:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco
348,Analyze Request for Quotation,start,Francois de Perrier,2011-01-02 15:32:00-05:00,Analyze Request for Quotation,Francois de Perrier,10,Variant 9,9,Fluxicon Disco

In [6]:
case = case.sort_values(by='time:timestamp')
case.head()

,concept:name,lifecycle:transition,org:resource,time:timestamp,Activity,Resource,case:concept:name,case:variant,case:variant-index,case:creator
344,Create Purchase Requisition,start,Esmana Liubiata,2011-01-02 02:52:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco
345,Create Purchase Requisition,complete,Esmana Liubiata,2011-01-02 03:43:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco
346,Create Request for Quotation,start,Immanuel Karagianni,2011-01-02 10:25:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco
347,Create Request for Quotation,complete,Immanuel Karagianni,2011-01-02 10:32:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco
348,Analyze Request for Quotation,start,Francois de Perrier,2011-01-02 15:32:00-05:00,Analyze Request for Quotation,Francois de Perrier,10,Variant 9,9,Fluxicon Disco

In [26]:
resource_changed = case['Resource'] != case.shift(-1)['Resource']
activity_changed = case['Activity'] != case.shift(-1)['Activity']

# because of NaN at the end of the shifted dataframe, we always have True
resource_changed.iloc[-1] = False
activity_changed.iloc[-1] = False

# both conditions must be satisfied
handoff_occurred = resource_changed & activity_changed

case['handoff_occurred'] = handoff_occurred
case[['case:concept:name', 'Activity', 'Resource', 'handoff_occurred']]

344    False
345     True
346    False
347     True
348    False
349     True
350    False
351    False
352    False
353     True
354    False
355     True
356    False
357     True
358    False
359    False
360    False
361     True
362    False
363     True
364    False
365     True
366    False
367     True
368    False
369     True
371    False
370     True
372    False
373    False
374    False
375    False
376    False
377     True
378    False
379    False
dtype: bool

In [9]:
# case['handoff_frequency'] = 0
case.loc[case['handoff_occurred'] == True, 'handoff_frequency'] = 1
case.head()

,concept:name,lifecycle:transition,org:resource,time:timestamp,Activity,Resource,case:concept:name,case:variant,case:variant-index,case:creator,handoff_occurred,handoff_frequency
344,Create Purchase Requisition,start,Esmana Liubiata,2011-01-02 02:52:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco,False,NaN
345,Create Purchase Requisition,complete,Esmana Liubiata,2011-01-02 03:43:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco,True,1.0
346,Create Request for Quotation,start,Immanuel Karagianni,2011-01-02 10:25:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco,False,NaN
347,Create Request for Quotation,complete,Immanuel Karagianni,2011-01-02 10:32:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco,True,1.0
348,Analyze Request for Quotation,start,Francois de Perrier,2011-01-02 15:32:00-05:00,Analyze Request for Quotation,Francois de Perrier,10,Variant 9,9,Fluxicon Disco,False,NaN

In [10]:
handoff_start = case.loc[handoff_occurred, 'time:timestamp']
handoff_end = case.loc[handoff_occurred.shift(1, fill_value=False), 'time:timestamp']
case.loc[handoff_occurred, 'handoff_duration'] = handoff_end.values - handoff_start.values
case.head()

,concept:name,lifecycle:transition,org:resource,time:timestamp,Activity,Resource,case:concept:name,case:variant,case:variant-index,case:creator,handoff_occurred,handoff_frequency,handoff_duration
344,Create Purchase Requisition,start,Esmana Liubiata,2011-01-02 02:52:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT
345,Create Purchase Requisition,complete,Esmana Liubiata,2011-01-02 03:43:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 06:42:00
346,Create Request for Quotation,start,Immanuel Karagianni,2011-01-02 10:25:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT
347,Create Request for Quotation,complete,Immanuel Karagianni,2011-01-02 10:32:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 05:00:00
348,Analyze Request for Quotation,start,Francois de Perrier,2011-01-02 15:32:00-05:00,Analyze Request for Quotation,Francois de Perrier,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT

In [11]:
case['handoff_score'] = case['handoff_duration'] * case['handoff_frequency']
case

,concept:name,lifecycle:transition,org:resource,time:timestamp,Activity,Resource,case:concept:name,case:variant,case:variant-index,case:creator,handoff_occurred,handoff_frequency,handoff_duration,handoff_score
344,Create Purchase Requisition,start,Esmana Liubiata,2011-01-02 02:52:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
345,Create Purchase Requisition,complete,Esmana Liubiata,2011-01-02 03:43:00-05:00,Create Purchase Requisition,Esmana Liubiata,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 06:42:00,0 days 06:42:00
346,Create Request for Quotation,start,Immanuel Karagianni,2011-01-02 10:25:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
347,Create Request for Quotation,complete,Immanuel Karagianni,2011-01-02 10:32:00-05:00,Create Request for Quotation,Immanuel Karagianni,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 05:00:00,0 days 05:00:00
348,Analyze Request for Quotation,start,Francois de Perrier,2011-01-02 15:32:00-05:00,Analyze Request for Quotation,Francois de Perrier,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
349,Analyze Request for Quotation,complete,Francois de Perrier,2011-01-02 15:59:00-05:00,Analyze Request for Quotation,Francois de Perrier,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 20:51:00,0 days 20:51:00
350,Send Request for Quotation to Supplier,start,Karel de Groot,2011-01-03 12:50:00-05:00,Send Request for Quotation to Supplier,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
351,Send Request for Quotation to Supplier,complete,Karel de Groot,2011-01-03 13:07:00-05:00,Send Request for Quotation to Supplier,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
352,Create Quotation comparison Map,start,Karel de Groot,2011-01-03 13:31:00-05:00,Create Quotation comparison Map,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
353,Create Quotation comparison Map,complete,Karel de Groot,2011-01-03 14:28:00-05:00,Create Quotation comparison Map,Karel de Groot,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 07:16:00,0 days 07:16:00
354,Analyze Quotation Comparison Map,start,Anna Kaufmann,2011-01-03 21:44:00-05:00,Analyze Quotation Comparison Map,Anna Kaufmann,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
355,Analyze Quotation Comparison Map,complete,Anna Kaufmann,2011-01-03 22:05:00-05:00,Analyze Quotation Comparison Map,Anna Kaufmann,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 00:00:00,0 days 00:00:00
356,Choose best option,start,Nico Ojenbeer,2011-01-03 22:05:00-05:00,Choose best option,Nico Ojenbeer,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
357,Choose best option,complete,Nico Ojenbeer,2011-01-03 22:05:00-05:00,Choose best option,Nico Ojenbeer,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 01:48:00,0 days 01:48:00
358,Settle Conditions With Supplier,start,Karel de Groot,2011-01-03 23:53:00-05:00,Settle Conditions With Supplier,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
359,Settle Conditions With Supplier,complete,Karel de Groot,2011-01-04 04:31:00-05:00,Settle Conditions With Supplier,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
360,Create Purchase Order,start,Karel de Groot,2011-01-04 09:44:00-05:00,Create Purchase Order,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
361,Create Purchase Order,complete,Karel de Groot,2011-01-04 09:52:00-05:00,Create Purchase Order,Karel de Groot,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 16:57:00,0 days 16:57:00
362,Confirm Purchase Order,start,Carmen Finacse,2011-01-05 02:49:00-05:00,Confirm Purchase Order,Carmen Finacse,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
363,Confirm Purchase Order,complete,Carmen Finacse,2011-01-05 02:58:00-05:00,Confirm Purchase Order,Carmen Finacse,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 08:50:00,0 days 08:50:00
364,Deliver Goods Services,start,Kiu Kan,2011-01-05 11:48:00-05:00,Deliver Goods Services,Kiu Kan,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
365,Deliver Goods Services,complete,Kiu Kan,2011-01-07 01:19:00-05:00,Deliver Goods Services,Kiu Kan,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 07:35:00,0 days 07:35:00
366,Release Purchase Order,start,Tesca Lobes,2011-01-07 08:54:00-05:00,Release Purchase Order,Tesca Lobes,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
367,Release Purchase Order,complete,Tesca Lobes,2011-01-07 08:55:00-05:00,Release Purchase Order,Tesca Lobes,10,Variant 9,9,Fluxicon Disco,True,1.0,1 days 18:00:00,1 days 18:00:00
368,Approve Purchase Order for payment,start,Karel de Groot,2011-01-09 02:55:00-05:00,Approve Purchase Order for payment,Karel de Groot,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
369,Approve Purchase Order for payment,complete,Karel de Groot,2011-01-09 02:56:00-05:00,Approve Purchase Order for payment,Karel de Groot,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 21:27:00,0 days 21:27:00
371,Send Invoice,complete,Karen Clarens,2011-01-10 00:23:00-05:00,Send Invoice,Karen Clarens,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
370,Send Invoice,start,Karen Clarens,2011-01-10 00:23:00-05:00,Send Invoice,Karen Clarens,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 14:22:00,0 days 14:22:00
372,Release Supplier's Invoice,start,Karalda Nimwada,2011-01-10 14:45:00-05:00,Release Supplier's Invoice,Karalda Nimwada,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
373,Release Supplier's Invoice,complete,Karalda Nimwada,2011-01-10 14:48:00-05:00,Release Supplier's Invoice,Karalda Nimwada,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
374,Settle Dispute With Supplier,start,Karalda Nimwada,2011-01-10 15:09:00-05:00,Settle Dispute With Supplier,Karalda Nimwada,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
375,Settle Dispute With Supplier,complete,Karalda Nimwada,2011-01-10 15:34:00-05:00,Settle Dispute With Supplier,Karalda Nimwada,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
376,Authorize Supplier's Invoice payment,start,Karalda Nimwada,2011-01-10 15:43:00-05:00,Authorize Supplier's Invoice payment,Karalda Nimwada,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
377,Authorize Supplier's Invoice payment,complete,Karalda Nimwada,2011-01-10 15:43:00-05:00,Authorize Supplier's Invoice payment,Karalda Nimwada,10,Variant 9,9,Fluxicon Disco,True,1.0,0 days 00:20:00,0 days 00:20:00
378,Pay Invoice,start,Pedro Alvares,2011-01-10 16:03:00-05:00,Pay Invoice,Pedro Alvares,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT
379,Pay Invoice,complete,Pedro Alvares,2011-01-10 16:16:00-05:00,Pay Invoice,Pedro Alvares,10,Variant 9,9,Fluxicon Disco,False,NaN,NaT,NaT

In [12]:
for (activity, group) in case[case['handoff_score'].notna()].groupby(by='Activity'):
    score_per_activity = group['handoff_score'].sum()
    print(f'{activity}: \t{score_per_activity}')

Analyze Quotation Comparison Map: 	0 days 00:00:00
Analyze Request for Quotation: 	0 days 20:51:00
Approve Purchase Order for payment: 	0 days 21:27:00
Authorize Supplier's Invoice payment: 	0 days 00:20:00
Choose best option: 	0 days 01:48:00
Confirm Purchase Order: 	0 days 08:50:00
Create Purchase Order: 	0 days 16:57:00
Create Purchase Requisition: 	0 days 06:42:00
Create Quotation comparison Map: 	0 days 07:16:00
Create Request for Quotation: 	0 days 05:00:00
Deliver Goods Services: 	0 days 07:35:00
Release Purchase Order: 	1 days 18:00:00
Send Invoice: 	0 days 14:22:00